import {useMemo,useState} from "react";
import {ShoppingBag, Clock3, Bike, CheckCircle2, XCircle, IndianRupee, TrendingUp, ChevronRight} from "lucide-react";
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,BarChart,Bar,CartesianGrid} from "recharts";
import {sampleOrders,sampleTrend,sampleMenu} from "../data/sampleData";
import {useRealtimeTable} from "../hooks/useRealtimeTable";
import StatCard from "../components/StatCard";
import StatusBadge from "../components/StatusBadge";
import {money,shortDateTime} from "../utils/format";

export default function Dashboard(){
 const {rows:liveOrders}=useRealtimeTable("orders",sampleOrders); const {rows:menu}=useRealtimeTable("menu_items",sampleMenu);
 const orders=liveOrders.length?liveOrders:sampleOrders; const items=menu.length?menu:sampleMenu; const [range,setRange]=useState("Today");
 const today=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);return d},[]);
 const todayOrders=orders.filter(o=>new Date(o.created_at)>=today);
 const statuses={preparing:0,picked_up:0,delivered:0,cancelled:0}; todayOrders.forEach(o=>statuses[o.status]=(statuses[o.status]||0)+1);
 const revenue=todayOrders.filter(o=>o.status!=="cancelled").reduce((s,o)=>s+Number(o.total_amount||0),0);
 const best=items.slice(0,5).map((m,i)=>({name:m.name,orders:Math.max(3,12-i*2)}));
 const trend=sampleTrend.map((x,i)=>({...x,revenue:Math.round(x.revenue*(range==="Today"?1:range==="This Week"?1.1:1.35))}));
 return <div className="space-y-6">
  <section className="grid grid-cols-2 xl:grid-cols-4 gap-4"><StatCard label="Total Orders Today" value={todayOrders.length} icon={ShoppingBag} subtext="Live from orders table"/><StatCard label="Preparing" value={statuses.preparing} icon={Clock3} tone="gold"/><StatCard label="Picked Up for Delivery" value={statuses.picked_up} icon={Bike} tone="blue"/><StatCard label="Delivered" value={statuses.delivered} icon={CheckCircle2} tone="green"/></section>
  <section className="grid grid-cols-2 xl:grid-cols-4 gap-4"><StatCard label="Cancelled" value={statuses.cancelled} icon={XCircle} tone="danger"/><div className="card p-5 col-span-1 xl:col-span-3 flex flex-col md:flex-row md:items-center justify-between gap-5"><div><p className="muted">Revenue · {range}</p><div className="flex items-center gap-2 mt-1"><IndianRupee size={28}/><span className="text-4xl font-heading font-bold">{revenue.toLocaleString("en-IN")}</span></div><p className="text-xs text-chicken-green mt-2 flex items-center gap-1"><TrendingUp size={13}/> Healthy sales momentum</p></div><div className="segmented">{["Today","This Week","This Month"].map(x=><button key={x} className={range===x?"selected":""} onClick={()=>setRange(x)}>{x}</button>)}</div></div></section>
  <section className="grid xl:grid-cols-[1.6fr_1fr] gap-5"><div className="card p-5"><div className="section-head"><div><h2 className="section-title">Revenue trend</h2><p className="muted">Last 7 days</p></div><span className="live-pill"><i/> LIVE</span></div><div className="h-64 mt-4"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid vertical={false} strokeDasharray="3 5"/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} width={45}/><Tooltip formatter={v=>[money(v),"Revenue"]}/><Line type="monotone" dataKey="revenue" stroke="#D62828" strokeWidth={3} dot={{r:4}} activeDot={{r:6}}/></LineChart></ResponsiveContainer></div></div>
  <div className="card p-5"><div className="section-head"><div><h2 className="section-title">Best-selling items</h2><p className="muted">Top 5 by orders</p></div></div><div className="h-64 mt-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={best} layout="vertical" margin={{left:5,right:10}}><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={105} axisLine={false} tickLine={false} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="orders" fill="#FFB703" radius={[0,8,8,0]}/></BarChart></ResponsiveContainer></div></div></section>
  <section className="grid xl:grid-cols-[1.6fr_1fr] gap-5"><div className="card overflow-hidden"><div className="section-head p-5 border-b border-black/5"><div><h2 className="section-title">Live order feed</h2><p className="muted">Newest orders first</p></div><span className="live-pill"><i/> REALTIME</span></div><div className="divide-y divide-black/5">{orders.slice(0,6).map(o=><div className="order-row" key={o.id}><div className="order-id">{o.id}</div><div className="min-w-0 flex-1"><p className="font-medium truncate">{o.customer_name}</p><p className="text-xs text-gray-500 truncate">{(o.items||[]).map(i=>`${i.quantity||1}× ${i.name}`).join(", ")}</p></div><div className="text-right"><p className="font-semibold">{money(o.total_amount)}</p><StatusBadge status={o.status}/></div><div className="text-xs text-gray-400 hidden md:block w-28 text-right">{shortDateTime(o.created_at)}</div></div>)}</div></div>
  <div className="card p-5"><h2 className="section-title">Cancellation insight</h2><p className="muted mt-1">Today's cancelled orders</p><div className="mt-6 flex items-end justify-between"><span className="text-5xl font-heading font-bold text-chicken-danger">{statuses.cancelled}</span><span className="text-xs px-3 py-2 rounded-full bg-red-50 text-chicken-danger">Monitor closely</span></div><div className="mt-6 space-y-3">{["Customer Cancelled","Store Rejected"].map(reason=><div key={reason} className="flex items-center justify-between"><span className="text-sm">{reason}</span><span className="font-semibold">{todayOrders.filter(o=>o.status==="cancelled"&&o.cancelled_reason===reason).length}</span></div>)}</div><div className="mt-7 p-4 rounded-2xl bg-chicken-cream"><p className="text-sm font-medium">Tip</p><p className="text-xs text-gray-500 mt-1">Keep rejection reasons consistent so this insight stays useful.</p></div></div></section>
 </div>
}