import {useState} from "react"; import {Plus,Search,Edit3,Trash2,ImagePlus} from "lucide-react"; import {supabase,supabaseConfigured,MENU_BUCKET} from "../lib/supabase"; import {sampleMenu} from "../data/sampleData"; import {useRealtimeTable} from "../hooks/useRealtimeTable"; import {money} from "../utils/format"; import Modal from "../components/Modal";
const cats=["Burgers","Zinger","Wraps","Fries","Chicken Strips","Momos","Combos","Fried Chicken"];
export default function MenuStudio(){const {rows}=useRealtimeTable("menu_items",sampleMenu);const menu=rows.length?rows:sampleMenu;const [search,setSearch]=useState("");const [open,setOpen]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState({name:"",price:"",category:"Burgers",description:"",is_available:true,image_url:""});const filtered=menu.filter(x=>x.name.toLowerCase().includes(search.toLowerCase()));
 const reset=()=>{setForm({name:"",price:"",category:"Burgers",description:"",is_available:true,image_url:""});setEditing(null);};
 const save=async e=>{e.preventDefault();if(!supabaseConfigured)return alert("Connect Supabase first. Preview data is read-only.");let image=form.image_url;const file=e.target.image.files[0];if(file){const path=`${Date.now()}-${file.name.replace(/\\s+/g,"-")}`;const {error}=await supabase.storage.from(MENU_BUCKET).upload(path,file);if(error)return alert(error.message);image=supabase.storage.from(MENU_BUCKET).getPublicUrl(path).data.publicUrl}const payload={...form,price:Number(form.price),image_url:image||null};if(editing)await supabase.from("menu_items").update(payload).eq("id",editing);else await supabase.from("menu_items").insert(payload);setOpen(false);reset();};
 const toggle=async item=>{if(supabaseConfigured)await supabase.from("menu_items").update({is_available:!item.is_available}).eq("id",item.id)}; const del=async id=>{if(confirm("Delete this menu item?")&&supabaseConfigured)await supabase.from("menu_items").delete().eq("id",id)};
 return <div className="space-y-6"><div className="page-actions"><div><h2 className="section-title text-2xl">Menu Studio</h2><p className="muted mt-1">Make your customer menu match the kitchen.</p></div><div className="flex gap-2"><div className="search-box"><Search size={17}/><input placeholder="Search menu…" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="btn primary" onClick={()=>{reset();setOpen(true)}}><Plus size={18}/> Add New Item</button></div></div>
 <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-5">{filtered.map(item=><article className="menu-card" key={item.id}><div className="menu-photo"><img src={item.image_url} alt={item.name}/><span className={`availability ${item.is_available?"in":"out"}`}>{item.is_available?"In stock":"Out of stock"}</span></div><div className="p-4"><div className="flex justify-between gap-3"><div><p className="text-xs text-gray-500">{item.category}</p><h3 className="font-heading font-bold text-lg mt-1">{item.name}</h3></div><p className="font-heading font-bold text-lg">{money(item.price)}</p></div><p className="text-sm text-gray-500 mt-2 line-clamp-2">{item.description}</p><div className="flex items-center justify-between mt-5"><button className={`switch ${item.is_available?"on":""}`} onClick={()=>toggle(item)}><span/></button><div className="flex gap-1"><button className="action-btn" onClick={()=>{setEditing(item.id);setForm({name:item.name,price:item.price,category:item.category,description:item.description||"",is_available:item.is_available,image_url:item.image_url||""});setOpen(true)}}><Edit3 size={16}/></button><button className="action-btn danger" onClick={()=>del(item.id)}><Trash2 size={16}/></button></div></div></div></article>)}</div>
 <Modal open={open} onClose={()=>{setOpen(false);reset()}} title={editing?"Edit menu item":"Add new menu item"}><form onSubmit={save} className="space-y-4"><label className="field-label">Item name<input className="input" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Zinger Burger"/></label><div className="grid sm:grid-cols-2 gap-4"><label className="field-label">Price<input className="input" required type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="179"/></label><label className="field-label">Category<select className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select></label></div><label className="field-label">Description<textarea className="input min-h-24" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Short, appetizing description"/></label><label className="field-label">Image<input className="input file-input" type="file" name="image" accept="image/*"/><span className="help"><ImagePlus size={14}/> Stored in Supabase Storage</span></label><div className="flex items-center justify-between p-4 rounded-2xl bg-chicken-cream"><div><p className="font-medium text-sm">Available for customers</p><p className="text-xs text-gray-500">Turn off when the kitchen is out.</p></div><button type="button" className={`switch ${form.is_available?"on":""}`} onClick={()=>setForm({...form,is_available:!form.is_available})}><span/></button></div><button className="btn primary w-full">{editing?"Save changes":"Create item"}</button></form></Modal>
 </div>
}